language: generic
sudo: required
services:
    - docker

before_install:
    - docker build --tag diegodaudt/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true diegodaudt/docker-react npm run test
